//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public short IdArticulo { get; set; }
        public short SubCategoria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaRecibido { get; set; }
        public short Estado { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string NombreDueno { get; set; }
        public System.Guid IngresadoPor { get; set; }
    
        public virtual SubCategoria SubCategoria1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
